# -*- coding: utf-8 -*-
"""Taxonomy: 4 hub lon (theo linh vuc do) + 10 hub cong nghe."""

MAIN = [
 dict(slug='do-muc-endress-hauser', hero_sku='FMR51', tone='m-level', catalog='Level',
      name='Thiết bị đo mức Endress+Hauser',
      short='Đo mức liên tục',
      nav='Thiết bị đo mức'),
 dict(slug='do-ap-suat-endress-hauser', hero_sku='PMP71B', tone='m-press', catalog='Pressure',
      name='Thiết bị đo áp suất Endress+Hauser',
      short='Đo áp suất & chênh áp',
      nav='Thiết bị đo áp suất'),
 dict(slug='cong-tac-muc-endress-hauser', hero_sku='FTL51', tone='m-point', catalog='Point Level',
      name='Công tắc báo mức Endress+Hauser',
      short='Báo mức giới hạn',
      nav='Công tắc báo mức'),
 dict(slug='do-nhiet-do-endress-hauser', hero_sku='TM111', tone='m-temp', catalog='Temperature',
      name='Thiết bị đo nhiệt độ Endress+Hauser',
      short='Đo nhiệt độ quá trình',
      nav='Thiết bị đo nhiệt độ'),
]

# tech hubs: match by (catalog, category) pairs
TECH = [
 dict(slug='radar-do-muc-micropilot', hero_sku='FMR51', tone='m-level', parent='do-muc-endress-hauser',
      name='Radar đo mức Micropilot',
      match=[('Level','Radar Level (Micropilot)')]),
 dict(slug='radar-dan-song-levelflex', hero_sku='FMP51', tone='m-level', parent='do-muc-endress-hauser',
      name='Radar dẫn sóng Levelflex',
      match=[('Level','Guided Radar (Levelflex)')]),
 dict(slug='sieu-am-do-muc-prosonic', hero_sku='FMU30', tone='m-level', parent='do-muc-endress-hauser',
      name='Cảm biến siêu âm đo mức Prosonic',
      match=[('Level','Ultrasonic (Prosonic)')]),
 dict(slug='do-muc-thuy-tinh-deltapilot-waterpilot', hero_sku='FMX21', tone='m-level', parent='do-muc-endress-hauser',
      name='Đo mức thủy tĩnh Deltapilot & Waterpilot',
      match=[('Level','Hydrostatic Level'),('Pressure','Deltapilot Hydrostatic Level'),
             ('Pressure','Waterpilot Level Probes')]),
 dict(slug='cam-bien-ap-suat-cerabar-ceraphant', hero_sku='PMP71B', tone='m-press', parent='do-ap-suat-endress-hauser',
      name='Cảm biến áp suất Cerabar & công tắc Ceraphant',
      match=[('Pressure','Cerabar Pressure Transmitters'),('Pressure','Pressure Switches (Ceraphant)')]),
 dict(slug='cam-bien-chenh-ap-deltabar', hero_sku='PMD75B', tone='m-press', parent='do-ap-suat-endress-hauser',
      name='Cảm biến chênh áp Deltabar',
      match=[('Pressure','Deltabar Differential Pressure'),('Pressure','Differential Pressure Level (Deltabar)'),
             ('Level','Differential Pressure Level (Deltabar)')]),
 dict(slug='cong-tac-muc-rung-liquiphant-soliphant', hero_sku='FTL51', tone='m-point', parent='cong-tac-muc-endress-hauser',
      name='Công tắc mức kiểu rung Liquiphant & Soliphant',
      match=[('Point Level','Point Level - Vibronic (Liquiphant)'),
             ('Point Level','Point Level - Vibronic (Soliphant)')]),
 dict(slug='cong-tac-muc-dien-dung-dan-dien', hero_sku='FMI21', tone='m-point', parent='cong-tac-muc-endress-hauser',
      name='Công tắc mức điện dung & dẫn điện',
      match=[('Point Level','Point Level - Capacitance (Liquicap)'),
             ('Point Level','Point Level - Capacitance Solids (Minicap/Nivector)'),
             ('Point Level','Point Level - Conductive (Liquipoint)'),
             ('Level','Capacitance (Liquicap)')]),
 dict(slug='bo-chuyen-doi-tin-hieu-nhiet-itemp', hero_sku='TMT82', tone='m-temp', parent='do-nhiet-do-endress-hauser',
      name='Bộ chuyển đổi tín hiệu nhiệt iTEMP',
      match=[('Temperature','Temperature Transmitters')]),
 dict(slug='nhiet-ke-cong-nghiep-itherm-omnigrad', hero_sku='TM411', tone='m-temp', parent='do-nhiet-do-endress-hauser',
      name='Nhiệt kế công nghiệp iTHERM & Omnigrad',
      match=[('Temperature','Industrial Modular Thermometers'),
             ('Temperature','Compact Thermometers'),
             ('Temperature','Cable Probes'),
             ('Temperature','High Temperature Thermometers'),
             ('Temperature','Hygienic Modular Thermometers'),
             ('Temperature','Surface Thermometers')]),
]

CAT2MAIN = {m['catalog']: m['slug'] for m in MAIN}
